name: Release
on:
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.[0-9]+*
  release:
    types:
      - published
jobs:
  prep:
    name: Prepare release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_name != 'main' }}
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install build twine
          pip install .
          pip install ".[lint, test]"

      - name: Update version
        working-directory: .github/scripts
        id: version
        run: |
          ref="${{ github.ref_name }}"
          version="${ref#"v"}"
          python update_version.py -v "$version"
          python -c "import pywatershed; print('Version: ', pywatershed.__version__)"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build package
        run: python -m build
      
      - name: Check package
        run: twine check --strict dist/*
      
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Generate changelog
        id: cliff
        uses: orhun/git-cliff-action@v1
        with:
          config: cliff.toml
          args: --verbose --unreleased --tag ${{ steps.version.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md

      - name: Update changelog
        id: update-changelog
        run: |
          # move changelog
          clog="CHANGELOG_${{ steps.version.outputs.version }}.md"
          echo "changelog=$clog" >> $GITHUB_OUTPUT
          sudo mv "${{ steps.cliff.outputs.changelog }}" "$clog"
          
          # show current release changelog
          cat "$clog"
          
          # substitute full group names
          sed -i 's/#### Ci/#### Continuous integration/' "$clog"
          sed -i 's/#### Feat/#### New features/' "$clog"
          sed -i 's/#### Fix/#### Bug fixes/' "$clog"
          sed -i 's/#### Refactor/#### Refactoring/' "$clog"
          sed -i 's/#### Test/#### Testing/' "$clog"

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: ${{ steps.update-changelog.outputs.changelog }}

      # maybe shouldn't update the release branch, so it's truly
      # a snapshot of main branch at release time, including SHA
      # 
      # - name: Update release branch
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |
      #     ver="${{ steps.version.outputs.version }}"
      #     changelog=$(cat ${{ steps.update-changelog.outputs.changelog }} | grep -v "### Version $ver")
      #     
      #     # commit and push changes
      #     git config core.sharedRepository true
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add -A
      #     git commit -m "ci(release): set version to ${{ steps.version.outputs.version }}"
      #     git push origin "${{ github.ref_name }}"

      - name: Draft release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          version=$(python .github/scripts/update_version.py -g)
          title="pywatershed $version"
          notes=$(cat "changelog/CHANGELOG_$version.md" | grep -v "### Version $version")
          gh release create "$version" \
            --target "${{ github.sha }}" \
            --title "$title" \
            --notes "$notes" \
            --draft \
            --latest

  publish:
    name: Publish package
    # runs only when GitHub release is published (manually promoted from draft)
    if: github.event_name == 'release' && github.repository_owner == 'EC-USGS'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install twine

      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      - name: Check package
        run: twine check --strict dist/*

      - name: Publish package
        run: twine upload dist/*

  reset:
    name: Draft reset PR
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install ".[lint, test]"

      - name: Get release tag
        uses: oprypin/find-latest-tag@v1
        id: latest_tag
        with:
          repository: ${{ github.repository }}
          releases-only: true

      - name: Draft reset PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # create reset branch from main
          reset_branch="post-release-${{ steps.latest_tag.outputs.tag }}-reset"
          git switch -c $reset_branch

          # increment minor version
          major_version=$(echo "${{ steps.latest_tag.outputs.tag }}" | cut -d. -f1)
          minor_version=$(echo "${{ steps.latest_tag.outputs.tag }}" | cut -d. -f2)
          patch_version=0
          version="$major_version.$((minor_version + 1)).$patch_version"
          python .github/scripts/update_version.py -v "$version"

          # format Python files
          python .github/scripts/pull_request_prepare.py

          # commit and push reset branch
          git config core.sharedRepository true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ci(release): update to development version $version"
          git push -u origin $reset_branch

          # create PR back into main
          body='
          # Reinitialize for development

          Updates `main` for the next development cycle following a successful release. Increments the minor version number.
          '
          gh pr create -B "main" -H "$reset_branch" --title "Reset main branch" --draft --body "$body"